### ISSUE TITLE
error "path not found"

### ISSUE THREAD

**Issue by ThetaGamma** [jschirrmacher/tasmota-prometheus-gateway#123]
based on config mentioned in #122 

once I curl to the HTTP metric endpoint I get an error message
```
curl localhost:13000/metric 
{"error":"path not found"}%                                      
```

**Comment by jschirrmacher** [comment]
Thanks for creating this issue!

I think, the problem described here is, that you try `/metric`, but the program defines `/metrics`.

**Comment by ThetaGamma** [comment]
Oh my god, what an embarrassing mistake by me! And it's now in the internet forever... ;-) you're right, thanks!
